name: Rust

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: cargo test --all-targets
    - name: Run tests in release mode
      run: cargo test --all-targets --release
